- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
  # Harmony maps start
  - Aspid
  - Atlas
  - Barratry
  - Elkridge
  - Jellyfish
  - Mira
  - Omega
  - Prime
  - Scylla
  # Harmony maps end
