using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Harmony.JoinQueue;

[GenerateTypedNameReferences]
public sealed partial class QueueGui : UIScreen
{
    public QueueGui()
    {
        RobustXamlLoader.Load(this);
        SetAnchorPreset(Background, LayoutPreset.Wide);
        SetAnchorPreset(MainContainer, LayoutPreset.Wide);
    }

    public void UpdateInfo(int total, int position)
    {
        QueueTotal.Text = total.ToString();
        QueuePosition.Text = position.ToString();
    }

    public void UpdateBranding(TextureResource logoTexture, string serverName)
    {
        Logo.Texture = logoTexture;
        ServerName.Text = serverName;
    }
}
