name: Build & Test Debug

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]

jobs:
  build:
    if: github.actor != 'ImpstationBot' && github.event.pull_request.draft == false
    timeout-minutes: 70
    strategy:
      matrix:
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Master
      uses: actions/checkout@v4.2.2

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 10.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration DebugOpt --no-restore

    - name: Memory Info Before Tests
      run: free -h

    - name: Run Content.Tests
      run: |
        dotnet test \
          --no-build \
          --configuration DebugOpt \
          Content.Tests/Content.Tests.csproj \
          -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      shell: pwsh
      run: |
        dotnet test `
          --no-build `
          --configuration DebugOpt `
          Content.IntegrationTests/Content.IntegrationTests.csproj `
          --blame-hang `
          --blame-crash `
          -v normal `
          -- `
          NUnit.ConsoleOut=0 `
          NUnit.MapWarningTo=Failed `
          NUnit.NumberOfTestWorkers=1

    - name: Memory Info After Tests
      if: always()
      run: free -h

    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/**'

  ci-success:
    name: Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-24.04
    steps:
      - name: CI succeeded
        run: exit 0
